#! /bin/python3.9

import subprocess
import sys

add: str = sys.argv[1]
commit: str = sys.argv[2]

def run_command(command: str):
    print(command)
    process = subprocess.Popen(command.split(), stdout=subprocess.PIPE)
    print(str(process.args))
    if command.startswith("git push"):
        output, error = process.communicate()
    else:
        output, error = process.communicate()
    try:
        output = bytes(output).decode()
        error = bytes(error).decode()
        if not output:
            print("output: " + output)
        print("error: " + error)
    except TypeError:
        print()
        print("Format './git add_file commit_msg'")


def main():
    global add
    global commit
    if add == "" or add == " ":
        add = "."
    print("add: '" + add + "' commit: '" + commit + "' ")

    command = "git add " + add
    run_command(command)

    commit = commit.replace(" ", "_")
    command = 'git commit -m "' + commit + '"'
    run_command(command)

    command = "git push origin "
    run_command(command)


if __name__ == '__main__':
    main()
